[workspace]
members = [
    "apps/octopus-cli",
    "crates/kosong",
    "crates/brain",
    "crates/faf-units",
    "crates/faf-sim",
    "crates/petgraph-svg",
    "crates/faf-downloader",
    "plugins/example-http",
    "plugins/faf-units",
    "plugins/faf-party",
    "apps/docref",
    "apps/faf-sim-cli",
    "apps/qqbot",
    "apps/qqbot-core",
    "xtask",
]
resolver = "3"
