//! Command-line schema for `faf-sim-cli`.
//!
//! This module contains every `clap` argument, subcommand, and value enum used
//! by the binary. The actual command logic lives in sibling modules.

use std::path::PathBuf;

use clap::{Args, Parser, Subcommand, ValueEnum};
use faf_build_scheduler::AlgorithmKind;

#[derive(Parser, Debug)]
#[command(name = "faf-sim", about = "Headless FAF build-queue simulator")]
pub struct Cli {
    #[command(subcommand)]
    pub command: Command,
}

#[derive(Subcommand, Debug)]
pub enum Command {
    /// Run a build-queue simulation and emit events as NDJSON.
    Build {
        #[command(subcommand)]
        mode: BuildMode,
    },
    /// Generate a training dataset by simulating random build plans.
    Dataset {
        #[command(subcommand)]
        mode: DatasetMode,
    },
    /// Train a build-time prediction model.
    Train(TrainArgs),
    /// Predict the completion time of a build plan.
    Predict {
        #[command(subcommand)]
        mode: PredictMode,
    },
    /// Compute a build order that reaches an eco or unit target.
    Schedule {
        #[command(subcommand)]
        mode: ScheduleMode,
    },
}

#[derive(Subcommand, Debug)]
pub enum ScheduleMode {
    /// Find the fastest way to reach an eco target.
    Eco(ScheduleEcoArgs),
    /// Find the fastest way to build a target unit.
    Unit(ScheduleUnitArgs),
}

#[derive(Args, Debug, Clone)]
pub struct ScheduleEcoArgs {
    /// Scheduling algorithm to use.
    #[arg(long, value_enum, default_value_t = AlgorithmKind::Placeholder)]
    pub algorithm: AlgorithmKind,

    /// JSON file containing the initial EcoSnapshot.
    #[arg(short, long)]
    pub eco: PathBuf,

    /// JSON file containing the initial inventory as a list of UnitKind strings.
    #[arg(short, long)]
    pub inventory: Option<PathBuf>,

    /// JSON file containing the EcoTarget.
    #[arg(short, long)]
    pub target: PathBuf,

    /// Path to the FAF units JSON file used to build the BlueprintLibrary.
    #[arg(long, default_value = "plugins/faf-units/data/faf_units.json")]
    pub units_file: PathBuf,

    /// Maximum search time in seconds.
    #[arg(long, default_value = "2.0")]
    pub max_search_seconds: f64,

    /// Solver cap when validating each candidate plan.
    #[arg(long, default_value = "6000.0")]
    pub simulation_max_time_seconds: f64,

    /// Output path for the generated BuildQueue JSON.
    #[arg(short, long, default_value = "schedule_queue.json")]
    pub output: PathBuf,
}

#[derive(Args, Debug, Clone)]
pub struct ScheduleUnitArgs {
    #[arg(long, value_enum, default_value_t = AlgorithmKind::Placeholder)]
    pub algorithm: AlgorithmKind,

    #[arg(short, long)]
    pub eco: PathBuf,

    #[arg(short, long)]
    pub inventory: Option<PathBuf>,

    /// Target UnitKind or blueprint id.
    #[arg(short, long)]
    pub target: String,

    #[arg(long, default_value = "plugins/faf-units/data/faf_units.json")]
    pub units_file: PathBuf,

    #[arg(long, default_value = "2.0")]
    pub max_search_seconds: f64,

    #[arg(long, default_value = "6000.0")]
    pub simulation_max_time_seconds: f64,

    #[arg(short, long, default_value = "schedule_queue.json")]
    pub output: PathBuf,
}

#[derive(Subcommand, Debug)]
pub enum DatasetMode {
    /// Simulate random plans and write labeled samples to a SQLite database.
    Generate {
        /// Output SQLite database path.
        #[arg(short, long, default_value = "data/build_prediction_dataset.db")]
        output: PathBuf,
        /// Number of samples to generate.
        #[arg(short, long, default_value = "10000")]
        samples: usize,
        /// Maximum number of builders assigned to a single task.
        #[arg(long, default_value = "3")]
        max_builders_per_task: usize,
        /// Maximum number of targets inside a single task.
        #[arg(long, default_value = "5")]
        max_targets_per_task: usize,
        /// Path to the FAF units JSON file. When provided, builders and targets
        /// are sampled from real unit definitions instead of pure synthetic ranges.
        #[arg(long, default_value = "plugins/faf-units/data/faf_units.json")]
        units_file: PathBuf,
    },
    /// Print a completion-time histogram and summary for an existing dataset.
    Histogram {
        /// Path to the SQLite dataset.
        #[arg(short, long, default_value = "data/build_prediction_dataset.db")]
        dataset: PathBuf,
    },
}

#[derive(Args, Debug, Clone)]
pub struct TrainArgs {
    /// Path to the SQLite dataset generated by `dataset generate`.
    #[arg(short, long)]
    pub dataset: PathBuf,
    /// Directory where model checkpoints, config, and logs are written.
    #[arg(short, long, default_value = "data/build_prediction_artifacts")]
    pub output_dir: String,
    /// Number of training epochs.
    #[arg(short, long, default_value = "10")]
    pub epochs: usize,
    /// Batch size.
    #[arg(short, long, default_value = "64")]
    pub batch_size: usize,
    /// Hidden layer size.
    #[arg(long, default_value = "128")]
    pub hidden_size: usize,
    /// Learning rate.
    #[arg(long, default_value = "0.001")]
    pub learning_rate: f64,
    /// Dropout probability on the hidden layer.
    #[arg(long, default_value = "0.0")]
    pub dropout: f64,
    /// L2 weight decay for the Adam optimizer.
    #[arg(long, default_value = "0.0")]
    pub weight_decay: f64,
    /// Time-based loss weighting power.
    ///
    /// The training loss multiplies each sample by `raw_time^{-power}` before
    /// averaging. Positive values up-weight fast plans, which prevents the
    /// optimizer from ignoring the rare practical region in an imbalanced
    /// dataset. Too high a value can bias the model toward underpredicting.
    /// 0.0 disables weighting (standard MSE). Try 0.2–0.5 as a starting point.
    #[arg(long, default_value = "0.0")]
    pub time_weight_power: f64,
}

#[derive(Subcommand, Debug)]
pub enum PredictMode {
    /// Predict using a trained neural network.
    Nn(PredictNnArgs),
    /// Predict using the analytical solver.
    Solver(PredictSolverArgs),
}

#[derive(Args, Debug, Clone)]
pub struct PredictNnArgs {
    #[command(flatten)]
    pub shared: PredictShared,
    /// Directory containing the trained model artifacts.
    #[arg(short, long, default_value = "data/build_prediction_artifacts")]
    pub model_dir: String,
}

#[derive(Args, Debug, Clone)]
pub struct PredictSolverArgs {
    #[command(flatten)]
    pub shared: PredictShared,
    /// Safety cap on how many seconds the solver may run.
    #[arg(short, long, default_value = "6000")]
    pub max_time_seconds: f64,
}

#[derive(Args, Debug, Clone)]
pub struct PredictShared {
    /// JSON file with the initial economy snapshot.
    /// If omitted, the snapshot is derived from the plan's `initial_eco` field.
    #[arg(short, long)]
    pub eco: Option<PathBuf>,
    /// JSON file with the build plan (`BuildQueue`).
    #[arg(short, long)]
    pub plan: PathBuf,
}

#[derive(Subcommand, Debug)]
pub enum BuildMode {
    /// Run the simulation in active (manual-advance) mode.
    Active {
        /// JSON file describing the build queue.
        queue: PathBuf,
        #[command(flatten)]
        shared: BuildShared,
    },
    /// Run the simulation in passive (auto-play) mode.
    Passive {
        /// JSON file describing the build queue.
        queue: PathBuf,
        #[command(flatten)]
        shared: BuildShared,
        /// Real-world delay between simulation steps in milliseconds.
        #[arg(long, default_value = "50")]
        tick_interval_ms: u64,
    },
}

#[derive(Args, Debug, Clone, Copy)]
pub struct BuildShared {
    /// Simulation step size in seconds. Must be an integer >= 1.
    #[arg(short, long, default_value = "1")]
    pub dt_seconds: u32,
    /// Maximum simulation time in seconds. When omitted the simulation
    /// runs until the build queue is empty.
    #[arg(short, long)]
    pub max_time_seconds: Option<u32>,
    /// Output format for Ticked events.
    #[arg(short, long, value_enum, default_value_t = OutputFormat::Raw)]
    pub format: OutputFormat,
    /// How many seconds the simulation keeps ticking after the build queue is
    /// empty. A value of `0` stops immediately at completion and prints only
    /// the final result, suppressing intermediate events.
    #[arg(long, default_value_t = 30.0)]
    pub tail_seconds: f64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum)]
pub enum OutputFormat {
    /// Emit raw simulation events (the primitive data source).
    Raw,
    /// Emit Ticked events grouped into rates/storage/totals/derived.
    Grouped,
}
