//! CLI for the FAF build-queue simulator.
//!
//! This client uses `faf-sim-service` to run a simulation locally and emits the
//! streamed events as NDJSON. The CLI only needs to know how to start a
//! simulation in active or passive mode and subscribe to it by id.

use std::path::PathBuf;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;
use std::time::Duration;

use clap::{Args, Parser, Subcommand, ValueEnum};
use faf_build_prediction::model::predictor::EcoPredictorConfig;
use faf_build_prediction::{
    generate_dataset, predict, train_with_ndarray, AdamConfig, GenerationConfig, Prediction,
    TrainingConfig,
};
use faf_sim::quantities::{StepTime, Time};
use faf_sim::sim::{BuildQueue, SimulationEvent};
use faf_sim::snapshot::{
    energy_available, energy_efficiency, energy_net, mass_net, mass_scaling_active,
    scaled_mass_income,
};
use faf_sim_service::{SimServiceEvent, SimulationId, SimulationReceiver, SimulationService};

#[derive(Parser, Debug)]
#[command(name = "faf-sim", about = "Headless FAF build-queue simulator")]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand, Debug)]
enum Command {
    /// Run a build-queue simulation and emit events as NDJSON.
    Build {
        #[command(subcommand)]
        mode: BuildMode,
    },
    /// Generate a training dataset by simulating random build plans.
    Dataset {
        #[command(subcommand)]
        mode: DatasetMode,
    },
    /// Train a build-time prediction model.
    Train(TrainArgs),
    /// Predict the completion time of a build plan using a trained model.
    Predict(PredictArgs),
}

#[derive(Subcommand, Debug)]
enum DatasetMode {
    /// Simulate random plans and write labeled samples to a SQLite database.
    Generate {
        /// Output SQLite database path.
        #[arg(short, long, default_value = "data/build_prediction_dataset.db")]
        output: PathBuf,
        /// Number of samples to generate.
        #[arg(short, long, default_value = "10000")]
        samples: usize,
        /// Practical time limit in seconds; slower plans are labeled NotPractical.
        #[arg(long, default_value = "600")]
        time_limit_seconds: f64,
        /// Maximum number of tasks in a generated plan.
        #[arg(long, default_value = "5")]
        max_tasks: usize,
        /// Maximum number of builders assigned to a single task.
        #[arg(long, default_value = "3")]
        max_builders_per_task: usize,
        /// Maximum number of targets inside a single task.
        #[arg(long, default_value = "5")]
        max_targets_per_task: usize,
    },
}

#[derive(Args, Debug, Clone)]
struct TrainArgs {
    /// Path to the SQLite dataset generated by `dataset generate`.
    #[arg(short, long)]
    dataset: PathBuf,
    /// Directory where model checkpoints, config, and logs are written.
    #[arg(short, long, default_value = "data/build_prediction_artifacts")]
    output_dir: String,
    /// Number of training epochs.
    #[arg(short, long, default_value = "10")]
    epochs: usize,
    /// Batch size.
    #[arg(short, long, default_value = "64")]
    batch_size: usize,
    /// Hidden layer size.
    #[arg(long, default_value = "128")]
    hidden_size: usize,
    /// Learning rate.
    #[arg(long, default_value = "0.001")]
    learning_rate: f64,
}

#[derive(Args, Debug, Clone)]
struct PredictArgs {
    /// Directory containing the trained model artifacts.
    #[arg(short, long, default_value = "data/build_prediction_artifacts")]
    model_dir: String,
    /// JSON file with the initial economy snapshot.
    #[arg(short, long)]
    eco: PathBuf,
    /// JSON file with the build plan (a list of `BuildTask`s).
    #[arg(short, long)]
    plan: PathBuf,
    /// Plans predicted to take longer than this are considered not practical.
    #[arg(long, default_value = "600")]
    practical_threshold_seconds: f64,
}

#[derive(Subcommand, Debug)]
enum BuildMode {
    /// Run the simulation in active (manual-advance) mode.
    Active {
        /// JSON file describing the build queue.
        queue: PathBuf,
        #[command(flatten)]
        shared: BuildShared,
    },
    /// Run the simulation in passive (auto-play) mode.
    Passive {
        /// JSON file describing the build queue.
        queue: PathBuf,
        #[command(flatten)]
        shared: BuildShared,
        /// Real-world delay between simulation steps in milliseconds.
        #[arg(long, default_value = "50")]
        tick_interval_ms: u64,
    },
}

#[derive(Args, Debug, Clone, Copy)]
struct BuildShared {
    /// Simulation step size in seconds. Must be an integer >= 1.
    #[arg(short, long, default_value = "1")]
    dt_seconds: u32,
    /// Maximum simulation time in seconds. When omitted the simulation
    /// runs until the build queue is empty.
    #[arg(short, long)]
    max_time_seconds: Option<u32>,
    /// Output format for Ticked events.
    #[arg(short, long, value_enum, default_value_t = OutputFormat::Raw)]
    format: OutputFormat,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum)]
enum OutputFormat {
    /// Emit raw simulation events (the primitive data source).
    Raw,
    /// Emit Ticked events grouped into rates/storage/totals/derived.
    Grouped,
}

fn main() {
    let cli = Cli::parse();
    match cli.command {
        Command::Build { mode } => match mode {
            BuildMode::Active { queue, shared } => run_active(queue, shared),
            BuildMode::Passive {
                queue,
                shared,
                tick_interval_ms,
            } => run_passive(queue, shared, tick_interval_ms),
        },
        Command::Dataset { mode } => match mode {
            DatasetMode::Generate {
                output,
                samples,
                time_limit_seconds,
                max_tasks,
                max_builders_per_task,
                max_targets_per_task,
            } => {
                if let Err(e) = generate_dataset(
                    &output,
                    GenerationConfig {
                        sample_count: samples,
                        time_limit_seconds,
                        max_tasks,
                        max_builders_per_task,
                        max_targets_per_task,
                    },
                ) {
                    eprintln!("Dataset generation failed: {e}");
                    std::process::exit(1);
                }
            }
        },
        Command::Train(args) => {
            let model_config = EcoPredictorConfig::new().with_hidden_size(args.hidden_size);
            let optimizer_config = AdamConfig::new();
            let config = TrainingConfig::new(model_config, optimizer_config)
                .with_num_epochs(args.epochs)
                .with_batch_size(args.batch_size)
                .with_learning_rate(args.learning_rate);

            train_with_ndarray(&args.output_dir, &args.dataset, config);
        }
        Command::Predict(args) => {
            let eco = read_json::<faf_sim::EcoSnapshot>(&args.eco);
            let plan = read_json::<Vec<faf_sim::BuildTask>>(&args.plan);

            match predict(
                args.model_dir.as_ref(),
                &eco,
                &plan,
                args.practical_threshold_seconds,
            ) {
                Ok(Prediction {
                    predicted_time_seconds,
                    is_practical,
                }) => {
                    println!(
                        "{}",
                        serde_json::to_string(&serde_json::json!({
                            "predicted_time_seconds": predicted_time_seconds,
                            "is_practical": is_practical,
                        }))
                        .expect("serialize prediction")
                    );
                }
                Err(e) => {
                    eprintln!("Prediction failed: {e}");
                    std::process::exit(1);
                }
            }
        }
    }
}

fn read_json<T: serde::de::DeserializeOwned>(path: &PathBuf) -> T {
    let text = std::fs::read_to_string(path).unwrap_or_else(|e| {
        eprintln!("Failed to read {}: {}", path.display(), e);
        std::process::exit(1);
    });
    serde_json::from_str(&text).unwrap_or_else(|e| {
        eprintln!("Failed to parse {}: {}", path.display(), e);
        std::process::exit(1);
    })
}

/// Parse the build queue and validate the step time from CLI arguments.
fn parse_queue_and_dt(queue: PathBuf, shared: BuildShared) -> (BuildQueue, StepTime, Option<Time>) {
    let json = std::fs::read_to_string(&queue).unwrap_or_else(|e| {
        eprintln!("Failed to read {}: {}", queue.display(), e);
        std::process::exit(1);
    });
    let queue: BuildQueue = serde_json::from_str(&json).unwrap_or_else(|e| {
        eprintln!("Failed to parse build queue: {}", e);
        std::process::exit(1);
    });

    let dt = StepTime::from_seconds(shared.dt_seconds).unwrap_or_else(|| {
        eprintln!("dt_seconds must be >= 1");
        std::process::exit(1);
    });
    let max_time = shared.max_time_seconds.map(|s| Time::from_raw(s as f64));

    (queue, dt, max_time)
}

/// Subscribe to a simulation, exiting the process on failure.
fn subscribe(service: &SimulationService, id: SimulationId) -> SimulationReceiver {
    service.subscribe(id).unwrap_or_else(|e| {
        eprintln!("Failed to subscribe to simulation: {e}");
        std::process::exit(1);
    })
}

/// Run in active mode.
///
/// The service does not auto-step in active mode, so we drive it from a
/// background thread that repeatedly sends `Advance` commands until the
/// simulation reports it is finished.
fn run_active(queue: PathBuf, shared: BuildShared) {
    let (queue, dt, max_time) = parse_queue_and_dt(queue, shared);

    let service = SimulationService::new();
    let id = service.start_active_sim(queue, dt, max_time);
    let rx = subscribe(&service, id);

    let is_finished = Arc::new(AtomicBool::new(false));
    let driver = service.clone();
    let finished = Arc::clone(&is_finished);
    std::thread::spawn(move || {
        while !finished.load(Ordering::SeqCst) {
            if driver.advance(id, dt).is_err() {
                break;
            }
            std::thread::sleep(Duration::from_millis(1));
        }
    });

    consume_events(rx, &is_finished, shared.format);
}

/// Run in passive mode.
///
/// The service auto-steps, so we only need to consume and print events.
fn run_passive(queue: PathBuf, shared: BuildShared, tick_interval_ms: u64) {
    let (queue, dt, max_time) = parse_queue_and_dt(queue, shared);

    let service = SimulationService::new();
    let id = service.start_passive_sim(queue, dt, max_time, tick_interval_ms);
    let rx = subscribe(&service, id);

    let is_finished = Arc::new(AtomicBool::new(false));
    consume_events(rx, &is_finished, shared.format);
}

/// Print simulation events as NDJSON until the stream ends or the simulation
/// finishes.
fn consume_events(rx: SimulationReceiver, is_finished: &Arc<AtomicBool>, format: OutputFormat) {
    while let Ok(event) = rx.recv() {
        match event {
            SimServiceEvent::Simulation(sim_event) => {
                print_event(&sim_event, format);
                if matches!(sim_event, SimulationEvent::Finished) {
                    is_finished.store(true, Ordering::SeqCst);
                    break;
                }
            }
            SimServiceEvent::Control(_) => {
                // Control events are not emitted as NDJSON by the CLI.
            }
        }
    }
}

fn print_event(event: &SimulationEvent, format: OutputFormat) {
    match event {
        SimulationEvent::Ticked(snapshot) if format == OutputFormat::Grouped => {
            let grouped = grouped_tick_json(snapshot);
            println!(
                "{}",
                serde_json::to_string(&grouped).expect("serialize grouped tick")
            );
        }
        _ => {
            println!("{}", serde_json::to_string(event).expect("serialize event"));
        }
    }
}

fn grouped_tick_json(s: &faf_sim::sim::EcoSnapshot) -> serde_json::Value {
    serde_json::json!({
        "Ticked": {
            "time": s.time,
            "rates": {
                "production_per_second_mass": s.production_per_second_mass,
                "production_per_second_energy": s.production_per_second_energy,
                "maintenance_consumption_per_second_energy": s.maintenance_consumption_per_second_energy,
                "mass_drain": s.mass_drain,
                "energy_drain": s.energy_drain,
            },
            "storage": {
                "mass_storage": s.mass_storage,
                "mass_storage_cap": s.mass_storage_cap,
                "energy_storage": s.energy_storage,
                "energy_storage_cap": s.energy_storage_cap,
            },
            "totals": {
                "total_mass_spent": s.total_mass_spent,
                "total_energy_spent": s.total_energy_spent,
            },
            "derived": {
                "energy_available": energy_available(s),
                "energy_net": energy_net(s),
                "scaled_mass_income": scaled_mass_income(s),
                "mass_net": mass_net(s),
                "energy_efficiency": energy_efficiency(s),
                "mass_scaling_active": mass_scaling_active(s),
            }
        }
    })
}
