[package]
name = "faf-db-web"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = { workspace = true }
dioxus = { workspace = true }
dioxus-router = "0.7.3"
faf-sim = { workspace = true, default-features = false, features = ["headless"] }
gloo-net = { workspace = true }
plotters = { version = "0.3.7", default-features = false, features = ["line_series", "full_palette"] }
plotters-canvas = "0.3"
serde = { workspace = true }
serde_json = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Window", "Storage", "WebSocket", "MessageEvent", "CloseEvent", "ErrorEvent", "Event", "console"] }
