[application]
name = "faf-db-web"

[web.app]
title = "FAF Unit DB"

[web.resource]
script = [
    "/uplot.iife.min.js",
    "/g6.min.js",
    "/faf_g6_bridge.js",
]
style = ["/uplot.min.css"]

[web.resource.dev]

[[web.proxy]]
backend = "http://localhost:8081/api/"

[[web.proxy]]
backend = "ws://localhost:8081/ws/"
