[package]
name = "faf-units-plugin"
version = "0.1.0"
edition = "2021"
authors = ["octopus contributors"]
description = "WASM plugin for querying and comparing FAF units."
license = "MIT"

[dependencies]
faf-units = { workspace = true }
extism-pdk = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[lib]
crate-type = ["cdylib"]
test = false
